### ISSUE TITLE
How do we integrate this into the domain & site?

### ISSUE THREAD

**Issue by Turtle84375** [Scratchblox-Official/status#2]
See the title. Is there a way to integrate the contents of this repo into the main one? Otherwise, we're going to need a subdomain, preferrably https://status.scratchblox.tk. @Ancoder2009, is that possible to configure?

**Comment by Ancoder2009** [comment]
Here

**Comment by Turtle84375** [comment]
> Here

...here?

**Comment by Ancoder2009** [comment]
> > Here
> 
> ...here?

no

**Comment by Turtle84375** [comment]
> > > Here
> > 
> > 
> > ...here?
> 
> no

I'm a little confused.

**Comment by Ancoder2009** [comment]
> > > > Here
> > > 
> > > 
> > > ...here?
> > 
> > 
> > no
> 
> I'm a little confused.

you cant

**Comment by Ancoder2009** [comment]
> > > > > Here
> > > > 
> > > > 
> > > > ...here?
> > > 
> > > 
> > > no
> > 
> > 
> > I'm a little confused.
> 
> you cant

wait ill do it

**Comment by Ancoder2009** [comment]
> > > > > Here
> > > > 
> > > > 
> > > > ...here?
> > > 
> > > 
> > > no
> > 
> > 
> > I'm a little confused.
> 
> you cant

wait ill do it

**Comment by Turtle84375** [comment]
> > > > > > Here
> > > > > 
> > > > > 
> > > > > ...here?
> > > > 
> > > > 
> > > > no
> > > 
> > > 
> > > I'm a little confused.
> > 
> > 
> > you cant
> 
> wait ill do it

Allright, thanks.
